"""empty message

Revision ID: 113864bb0a8d
Revises: 3fcaa3109cab
Create Date: 2024-11-08 17:17:48.744817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113864bb0a8d'
down_revision = '3fcaa3109cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qusetion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auth_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qusetion')
    # ### end Alembic commands ###
