"""empty message

Revision ID: d5f25501aa73
Revises: 42f8f12b818c
Create Date: 2024-11-08 12:39:54.095078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f25501aa73'
down_revision = '42f8f12b818c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.drop_column('used')

    # ### end Alembic commands ###
